### PR TITLE
Use travis for testing

### PR DESCRIPTION
**Pull request by jpommerening**
I took the liberty to enable Travis for this repository. Funnily, it's listing the repo twice and I don't know which is this one and which is the fork: https://travis-ci.org/profile/osx-cross

Anyways, I took to stackoverflow and found this: http://stackoverflow.com/questions/20396325/using-travis-ci-to-test-homebrew-tap

I have no idea if it works, so let's find out :)

### CODE REVIEW

**Comment by jpommerening** [comment]
Looks like `brew install -v` wasn't such a good idea for something like gcc (log gets truncated at 10k lines). Working on it …

**Comment by jpommerening** [comment]
> /private/tmp/avr-gcc-NuiKuj/gcc-4.9.2/build/./gcc/xgcc -B/private/tmp/avr-gcc-NuiKuj/gcc-4.9.2/build/./gcc/ -B/usr/local/Cellar/avr-gcc/4.9.2/avr/bin/ -B/usr/local/Cellar/a
> 
> The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).
> 
> The build has been terminated.

Hrmpf, this is getting tricky.
If we `brew install -v`, the build gets terminated because it does not log anything, if we omit the `-v` flag, the build gets terminated because it logs too much.

Any ideas? I'll continue working on this after work…

**Comment by leojrfs** [comment]
@jpommerening whats the status of this? can you detail what you have tried?

**Comment by jpommerening** [comment]
Hey there, sorry for the delay.

I never managed to get it below Travis' timeout policies. Mights as well close this PR, right?

**Pull request closed without merging**
