### PR TITLE
Initial simavr formula

### PR DESCRIPTION
**Pull request by jedahan**
Fixing of issue #12 
Right now its a head-only formula.

### CODE REVIEW

**Comment by larsimmisch** [comment]
Thank you - I'll try to look at it this week.

**Comment by larsimmisch** [comment]
It builds. Thank you.

I think I'd prefer the patch inline, but I can do that later - but I'd obviously appreciate it if you did it.

**Comment by ladislas** [comment]
> I think I'd prefer the patch inline, but I can do that later - but I'd obviously appreciate it if you did it.

what do you mean?

**Comment by larsimmisch** [comment]
Ah, I thought we had changed `avr-binutils.rb` to use an inline/embedded patch. But we haven't, so I think we can leave this as is and just merge the pull request.

See https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#patches for documentation on embedded patches.

I like them a little better than gist-style patches, in particular for small patches, because:
- everything is in one place
- you can install the formula offline

**Comment by ladislas** [comment]
for avr-binutils, the pull request is here #16 ;)

**Pull request merged**
