### PR TITLE
Update gcc to 6.2, fix minor issues in links and caveats, remove cloog and isl dependencies in 4.8

### LINKED ISSUE #34: Failed to "brew install avr-libc"
because of the changing of the "avr-binutils-size.patch"

it was changed to "https://gist.githubusercontent.com/larsimmisch/4190960/raw/16c6b9627f8451eeebd644a4b9a741edfdb0c45e/avr-binutils-size.patch"

### PR DESCRIPTION
**Pull request by ladislas**
this will fix https://github.com/osx-cross/homebrew-avr/issues/34, https://github.com/osx-cross/homebrew-avr/pull/22, https://github.com/osx-cross/homebrew-avr/issues/20

### CODE REVIEW

**Comment by ladislas** [comment]
this will fix https://github.com/osx-cross/homebrew-avr/issues/34, https://github.com/osx-cross/homebrew-avr/pull/22, https://github.com/osx-cross/homebrew-avr/issues/20

**Comment by ladislas** [comment]
@osx-cross/team it works well on my machine, I'll let you guys try it :)

no big changes so it should not break anything.

**Comment by leojrfs** [comment]
works for me

**Comment by ladislas** [comment]
so I can merge?

**Comment by leojrfs** [comment]
I think you should, it fixes problematic issues.

**Pull request merged**
