### PR TITLE
Add avr-libc as a resource, cleanup formula name and simplify installation process

### PR DESCRIPTION
**Pull request by ladislas**
Hi all --

As discussed here #49 and here #48 I've made a pull request to test the changes.

The resource thing only works for the latest version. 

I have a strange error with `@4` and `@5`

Can you guys give it a try?

### CODE REVIEW

**Comment by ladislas** [comment]
@osx-cross/team bump 🙇 :)

**Comment by leojrfs** [comment]
i cant currently test it, but if it works for you 👍

**Comment by ladislas** [comment]
well actually it only works for the latest version. I cannot get the older versions to compile. I don't know what's wrong...

**Comment by larsimmisch** [comment]
I looked at it and liked it, but I still haven't tested it (sorry - busy).

Go ahead and merge it.

**Comment by ladislas** [comment]
ahah 😄 I'm afraid that if I merge, people will get confused and we'll have a bunch of new issues we could avoid.

I'm not in a hurry, I prefer to let you guys test it before we merge that :)

**Comment by larsimmisch** [comment]
How did you test this? If I switch branches in `/usr/local/Homebrew/Library/Taps`, `brew install ./avr-gcc.rb` just switches the branch back to master. That seems to be a no-no these days.

Checking out a seperate repo also didn't work out for me:

```
Error: No available formula with the name "avr-gcc@6" 
In formula file: /Users/lars/Development/homebrew-avr/avr-gcc@6.rb
Expected to find class AvrGccAT6, but only found: AvrGcc.
```

**Comment by ladislas** [comment]
you have to cd to `/usr/local/Homebrew/Library/Taps/osx-cross/homebrew-avr` and then git checkout the right branch and then brew update

**Comment by larsimmisch** [comment]
homebrew confuses me these days:

```
lars@ohm ~$ cd $(brew --repository)
lars@ohm (stable) Homebrew$ cd Library/Taps/osx-cross/homebrew-avr/
lars@ohm (master) homebrew-avr$ git checkout update-formula 
Switched to branch 'update-formula'
Your branch is up-to-date with 'origin/update-formula'.
lars@ohm (update-formula) homebrew-avr$ brew update
Already up-to-date.
lars@ohm (master) homebrew-avr$ git status
On branch master
nothing to commit, working tree clean
```

As you see, `brew update` switches me back to master.

**Comment by ladislas** [comment]
hmm that's strange, it doesn't do that on mine... maybe you can clone the repo and merge update-formula to master and then try again 😆

**Comment by larsimmisch** [comment]
Good idea. Now I get:

```
In formula file: /usr/local/Homebrew/Library/Taps/osx-cross/homebrew-avr/avr-gcc@6.rb
Expected to find class AvrGccAT6, but only found: AvrGcc.
```

**Comment by ladislas** [comment]
@larsimmisch just fixed it

**Comment by ladislas** [comment]
I'm closing this one and opening a new one with avr-gcc 7.1

**Pull request closed without merging**
