### PR TITLE
Fix bottle upload and drop Big Sur

### PR DESCRIPTION
**Pull request by fauxpark**
Prereq for #324, and all other fixes that must go in before it.

### CODE REVIEW

**Comment by fauxpark** [comment]
`brew style` failures need to be solved in a separate, followup PR. What a mess.

**Comment by fauxpark** [comment]
Big Sur can also be dropped as Monterey is now the minimum supported version for Brew.

**Comment by ladislas** [comment]
> `brew style` failures need to be solved in a separate, followup PR. What a mess.

I've created a PR here for that https://github.com/osx-cross/homebrew-avr/pull/327

once it's green, I'll rebase your PR or cherry pick your changes in a new PR

**Comment by fauxpark** [comment]
This PR needs to go in first; the upload-artifact action is broken - see above.

**Comment by ladislas** [comment]
@fauxpark I've also update the actions in another PR https://github.com/osx-cross/homebrew-avr/pull/328

**Comment by fauxpark** [comment]
That's what this PR does already... nothing will be green until *this PR* goes in.

**Comment by ladislas** [comment]
Sorry I got confused. 
You upgraded to v3. Any reason not to use v4?

**Pull request merged**
