### PR TITLE
Bundle avr-libc to avr-gcc to resolve sandbox issue

### PR DESCRIPTION
**Pull request by cosmo0920**
This PR contains patches to fix issue #19 with `resource` syntax against `avr-gcc` formula.
Note that this PR is dramatically changes `avr-libc` installation process.

### CODE REVIEW

**Comment by ladislas** [comment]
this sounds very interesting to me! This way we could have different version of avr-gcc live happily together without interfering.

Only the most recent could be linked and the older one could be keg only.

what do you guys think? @osx-cross/team

**Comment by leojrfs** [comment]
It looks good :+1:

**Comment by ladislas** [comment]
@cosmo0920 I've been very busy for the past few months but I'm now back :)

does having avr-libc as a resource allow users to have multiple versions of avr-gcc compiled with their own avr-libc each time?

as i said here https://github.com/osx-cross/homebrew-avr/pull/23#issuecomment-249406098, a new PR is coming today that should fix different issues.

we can start from it to merge this PR, you'll just need a few changes.

**Comment by ladislas** [comment]
@cosmo0920 new PR merged. Will you have time to update this one/make a new one or do you want me to start working on it?

**Comment by cosmo0920** [comment]
I don't have enough time to resolve conflict and confirm working.
I'm closing this PR for now.

**Pull request closed without merging**
