### PR TITLE
:construction_worker: (ci): Upgrade actions/cache, upload-artifacts to v4

### PR DESCRIPTION
**Pull request by ladislas**

### CODE REVIEW

**Review by fauxpark — COMMENTED** [review]
The `brew tap-new` template still specifies actions/cache and actions/upload-artifact @ `v3` (latter changed from `main`) - we should probably keep that as is:
https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/tap-new.rb#L99

https://github.com/Homebrew/brew/pull/16347

**Comment by ladislas** [comment]
Okay I've got the answer to my question here. I'll merge your other PR then. Sorry for the back and forth.

**Comment by fauxpark** [comment]
All good. This is a particularly annoying chicken-and-egg problem, isn't it? 😄

**Comment by ladislas** [comment]
closing, already done in #325

**Pull request closed without merging**
