### PR TITLE
Add avr-gcc v11

### LINKED ISSUE #233: Support for avr-gcc 11
As the title says. Will (if yes, then when?) `avr-gcc@11` be available?

### PR DESCRIPTION
**Pull request by bartekpacia**
fix #233

### CODE REVIEW

**Comment by bartekpacia** [comment]
@ladislas I see that many (if not all) formulas in here have their bottles in this repo's releases tab https://github.com/osx-cross/homebrew-avr/releases. How can I get `avr-gcc` v11 in there? Or am I missing something [ highly possible :) ]?

**Comment by ladislas** [comment]
> I see that many (if not all) formulas in here have their bottles in this repo's releases tab [...]

Yes, this is normal, I must manually run the workflow as you are an external contributor. 

Can you fixup the commits to have just one commit + change the commit message to `avr-gcc@11 - add formula`

**Comment by bartekpacia** [comment]
@ladislas sure, done

 `bottle do` block points to gcc v10 tho

**Comment by ladislas** [comment]
Thanks! I'll start the workflow, let see if it works ;)

**Comment by bartekpacia** [comment]
apparently it fails because I didn't update the checksum

Should I compute SHA1 and SHA256 for https://ftp.gnu.org/gnu/gcc/gcc-11.1.0/gcc-11.1.0.tar.xz and update them?

**Comment by ladislas** [comment]
You can use the values from the CI output (`expected` / `actual`, the later being the right one).

Can you also remove the `bottle do` block?

**Comment by bartekpacia** [comment]
sure, applied your suggestions and force-pushed :)

**Comment by bartekpacia** [comment]
It's been running for 16 minutes, is it normal @ladislas?

**Comment by ladislas** [comment]
yes, you're build gcc from source, it can take up to 2 hours

**Comment by bartekpacia** [comment]
whoah, okay then:)

**Comment by bartekpacia** [comment]
also, will you make `avr-gcc@11` the default for `avr-gcc` formula, and require to specify a particular version to download older versions? That's pretty common, e.g `gcc` uses this

**Comment by bartekpacia** [comment]
aaand it failed. I think it's beacuse the newer GCC generates a different Intel HEX output – will try to fix it.

EDIT
That was probably the case - the c++ test on avr-gcc v11 generates a slightly different hex

**old hex**
```
:1000000010E0A0E6B0E0ECE7F0E003C0C895319660
:100010000D92A636B107D1F700D000D0CDB7DEB72C
:10002000209A8091600090916100A0916200B0914F
:10003000630089839A83AB83BC83FE0131969E0162
:100040002B5F3F4F41E08191882371F05FEF64E3C4
:100050009CE0515060409040E1F700C0000095B135
:10006000942795B98150F0CFE217F30761F790E03C
:0C00700080E00F900F900F900F9008950B
:06007C0001020304000074
:00000001FF
```

**new hex**
```
:1000000010E0A0E6B0E0ECE7F0E003C0C895319660
:100010000D92A636B107D1F700D000D0CDB7DEB72C
:10002000209A8091600090916100A0916200B0914F
:10003000630089839A83AB83BC83FE0131969E0162
:100040002B5F3F4F41E0819181110AC0E217F30716
:10005000D1F790E080E00F900F900F900F900895EF
:100060005FEF64E39CE0515060409040E1F700C0D6
:0C007000000095B1942795B98150E6CFAF
:06007C0001020304000074
:00000001FF
```

**Comment by bartekpacia** [comment]
Still fails...any ideas @ladislas?

**Comment by ladislas** [comment]
> Still fails...any ideas @ladislas?

I must run in again manually each time and I was asleep. CI started :)

**Comment by ladislas** [comment]
the hex issue was normal. I knew it would fail on that but it's okay. The only way to know is to build it first on your computer from source. But it takes too much time and CI never complains ;)

**Comment by bartekpacia** [comment]
That's exactly what I did - I built a HEX on my another Windows machine which has avr-gcc v11 installed. I already fixed that hex thing (but forgot that you didn't start the CI, so when I woke up I thought that's the new CI run that failed, and it was yesterday's CI run).

should work fine now

**Comment by ladislas** [comment]
CI is all green 🟢 Thanks for the PR, starting the publish workflow now.

**Comment by bartekpacia** [comment]
that's great, thanks🎉

> will you make `avr-gcc@11` the default for `avr-gcc` formula, and require to specify a particular version to download older versions? That's pretty common, e.g `gcc` uses this

what about this?

**Pull request closed without merging**
