### PR TITLE
Fix avr-gcc@5 build

### PR DESCRIPTION
**Pull request by fauxpark**
Attempting to fix this formula in order to clear #324

### CODE REVIEW

**Comment by fauxpark** [comment]
Despite the green, the build is failing. Since Homebrew have now disabled `isl@0.18` I suspect it may not be possible to build GCC 5 and this formula might need to be removed.

**Comment by ladislas** [comment]
we can keep it unbottled. people really needing this one can still build from source.
let's focus our effort on the most used versions first :)

**Comment by ladislas** [comment]
as you can see here, there are not a lot of users for this version.

https://qii404.me/github-release-statistics/

or here https://tooomm.github.io/github-release-stats/?username=osx-cross&repository=homebrew-avr

**Comment by ladislas** [comment]
@fauxpark I've removed gcc@5 from the repo with #345 

since the last release in Feb 2021 there has only been 221 downloads

image

the problem with building comes from the fact that isl@0.18 has been deprecated. I'm not sure it's worth the effort to also maintain isl@0.18 locally.

If you're okay, we can close this PR

**Comment by fauxpark** [comment]
Sounds good to me.

**Pull request closed without merging**
