### PR TITLE
avr-gcc: Fix building from scratch

### PR DESCRIPTION
**Pull request by pthariensflame**

### CODE REVIEW

**Comment by ladislas** [comment]
thanks @pthariensflame for the PR! May I ask which macOS version you are using? Are you not using bottles? Why do you need to build from scratch? Can you past the output of failure?

I've remove those two lines yesterday and bottles were built just fine on Catalina, High Sierra and Mojave.

**Comment by Feuerwerk** [comment]
@ladislas I updated my home-brew today and realized that i get errors. In my case i build from scratch because i enabled "--with-ATMega168pbSupport"

**Comment by ladislas** [comment]
makes sense, I'll add them back!

**Comment by ladislas** [comment]
It should be fixed, let me know if not.

**Comment by Feuerwerk** [comment]
Works perfectly, thanks :-)

**Comment by pthariensflame** [comment]
Yup, for me too!

**Pull request closed without merging**
