### PR TITLE
Add patch to fix argument type mismatch when compiling GCC 11

### PR DESCRIPTION
**Pull request by jmechnich**
This PR should fix issue #280.

After merging, the patch url will have to be adapted to point at this repo.

### CODE REVIEW

**Comment by ladislas** [comment]
Thanks for the PR!

if CI succeeds, can you make another PR with just the patch that I will merge directly and then edit this one to point to the patch inside this repo?

you can add your patch here

https://github.com/osx-cross/homebrew-avr/tree/main/Patch

**Comment by jmechnich** [comment]
How about just removing the change to the formula from this PR?

**Comment by jmechnich** [comment]
I guess the CI should succeed now that the changes to the formula are removed. As soon as this is merged, I will create another PR.

**Comment by ladislas** [comment]
thanks a lot!

You can now use

`https://raw.githubusercontent.com/osx-cross/homebrew-avr/main/Patch/avr-gcc-11-fix-argument-type-mismatch.patch`

**Comment by jmechnich** [comment]
> thanks a lot!
> 
> You can now use
> 
> `https://raw.githubusercontent.com/osx-cross/homebrew-avr/main/Patch/avr-gcc-11-fix-argument-type-mismatch.patch`

I have used the commit hash instead of `main` as, iirc, this was one of the complaints by the CI run yesterday. See #288 for the remainder of the fix.

**Pull request merged**
