### PR TITLE
Add gdb 7.8.2

### PR DESCRIPTION
**Pull request by jpommerening**
Here's my GDB formula, updated to 7.8.2 and indented to match the other ones.

### CODE REVIEW

**Comment by leojrfs** [comment]
@jpommerening is it properly tested?
@osx-cross/owners can anyone confirm it?

**Comment by jpommerening** [comment]
@leojrfs: Well, beyond "works for me" (or, "worked", hah…) … no.
Didn't have much time for tinkering with it lately.

**Comment by leojrfs** [comment]
lets merge it then, we will have a wider test base :smiley:

**Comment by jpommerening** [comment]
Haha, ok. It probably wont break anything that worked before :)

**Pull request merged**
