### PR TITLE
:alien: (binutils): Bump revision

### PR DESCRIPTION
**Pull request by ladislas**

### CODE REVIEW

**Comment by fauxpark** [comment]
Seems like it's not happy about the master->main rename :(

(neither is `brew update`, FTR)

**Comment by ladislas** [comment]
good catch! should be fixed now

**Comment by alswl** [comment]
Homebrew seems not support `main` branch name now.

**Comment by fauxpark** [comment]
Either run `brew tap --repair`, or force untap and re-tap `osx-cross/avr`.

**Comment by alswl** [comment]
```
brew tap --repair
==> osx-cross/avr: changed default branch name from master to main!
```

👍👍👍

**Pull request closed without merging**
