### PR TITLE
Update to GCC 10.2.0

### PR DESCRIPTION
**Pull request by rleh**

### CODE REVIEW

**Comment by rleh** [comment]
Oh, somehow I missed #192 :unamused:
Close?

**Comment by rleh** [comment]
I'm not sure how to understand to Azure CI error:
```
Generating script.
Script contents:
brew test-bot --root-url=https://dl.bintray.com/osx-cross/bottles-avr
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/666ba8b1-bdc0-43be-bfd9-2859025ec383.sh
Homebrew/homebrew-test-bot 4b9881e (Merge pull request #324 from MikeMcQuaid/homebrew_testing)
ARGV: --root-url=https://dl.bintray.com/osx-cross/bottles-avr
Error: Calling Homebrew.args is disabled! Use `args = <command>_args.parse` and pass `args` along the call chain instead.
Please report this issue to the osx-cross/test-bot tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/osx-cross/homebrew-test-bot/lib/test_bot.rb:415
```

---

Unfortunately, I don't have a macOS device available for testing, so I probably can't help much here.
The problem looked easier to fix, for https://github.com/modm-io/modm we need GCC10, let's see if someone can be found to help...

**Comment by salkinium** [comment]
> This branch is 397 commits behind Homebrew:master.  on Feb 3

cc @ladislas osx-cross/homebrew-test-bot is a touch out of date.

**Comment by rleh** [comment]
Probably because upstream homebrew-test-bot has removed the support for Azure pipelines: Homebrew/homebrew-test-bot/pull/325
https://github.com/osx-cross was deliberately ignored in the discussion.

[`test-bot` man-page](https://docs.brew.sh/Manpage#test-bot-options-formula):
> Only supports GitHub Actions as a CI provider. This is because Homebrew uses GitHub Actions and it’s freely available for public and private use with macOS and Linux workers.

So one way would be to migrate from Azure pipelines to Github Actions, but that is always pain for everyone without admin access to the repo/organization.

**Review by salkinium — APPROVED** [review]
This builds on my 10.14 macOS and I didn't notice any immediate regressions on my AVR projects.

**Comment by ladislas** [comment]
Thanks all for the help and inputs.

You're right, Azure was removed but osxcross is using its own fork of brew-test-bot. That being said the pipeline is out of date as macOS versions have changed. 

With the recent release of homebrew it's now easier than ever to use GitHub actions. But it takes time to migrate everything. The other drawback is that we will only support the latest macOS for pre built bottles. Former versions will need to build from source. It's not that bad as you usually build once and don't need to update gcc that often. 

I'll look into it over the holidays. I've been pretty busy lately.

**Comment by rleh** [comment]
Thank you!

I tried to implement Github Actions as a replacement for Azure pipelines in modm-ext/homebrew-avr#2, and except for one bug it seems to work.
As soon as it works, I'll open a pull request here.

https://github.com/modm-ext/homebrew-avr/runs/1583597340:
```
==> Running Formulae#formula!(modm-ext/avr/avr-gcc)
==> Determining dependencies...
==> brew fetch --retry gmp isl libmpc mpfr
==> Determining dependents...
==> Starting build of modm-ext/avr/avr-gcc
==> brew fetch --retry modm-ext/avr/avr-gcc --build-bottle --force
==> brew install --only-dependencies --verbose --build-bottle modm-ext/avr/avr-gcc
==> brew install --verbose --build-bottle modm-ext/avr/avr-gcc
==> brew audit modm-ext/avr/avr-gcc --online --git --skip-style
==> FAILED
modm-ext/avr/avr-gcc:
  * Files were found with references to the Homebrew shims directory.
    The offending files are:
      libexec/gcc/avr/9.3.0/install-tools/fixincl
Error: Files were found with references to the Homebrew shims directory.
The offending files are:
  libexec/gcc/avr/9.3.0/install-tools/fixincl

[...]

==> Detecting if avr-gcc--9.3.0.catalina.bottle.2.tar.gz is relocatable...
Warning: String '/usr/local/Homebrew' still exists in these files:
/usr/local/Cellar/avr-gcc/9.3.0/libexec/gcc/avr/9.3.0/install-tools/fixincl
 --> match '/usr/local/Homebrew/Library/Homebrew/shims/mac/super/sed' at offset 0x10500
Error: Bottle contains non-relocatable reference to /usr/local/Homebrew!
```

The error does not seem to occur on Linux, so it is hard for me to understand and fix the problem.

@ladislas or @salkinium Maybe you can help me?

**Comment by ladislas** [comment]
closed by #202

**Pull request closed without merging**
