### PR TITLE
Add AVRA

### LINKED ISSUE #221: Request for adding avra(assembly compiler) to the formulae
As in the title, can you add `avra`, the AVR assembly compiler, to the `homebrew-avr` formulae?

### PR DESCRIPTION
**Pull request by bartekpacia**
fix #221 

I just created the initial scaffold and am not sure how to continue.

@ggoraa maybe you want to help?

### CODE REVIEW

**Comment by ladislas** [comment]
Running CI to see what happens. you can also brew install avra on your computer to see if it works.

**Comment by ladislas** [comment]
@bartekpacia any news on this PR?

**Comment by bartekpacia** [comment]
No, I somehow lost interest in it, sorry! And now I don't have free time at all.

**Comment by ladislas** [comment]
Alright, I'll close, feel free to reopen in the future if needed

**Pull request closed without merging**
