### PR TITLE
Fix typo in AVaRICE formula description

### PR DESCRIPTION
**Pull request by carlossless**

### CODE REVIEW

**Comment by ladislas** [comment]
thanks a lot @carlossless! I'll merge the PR asap but first I want to use it to fix the CI testing (#103).

**Comment by carlossless** [comment]
sure! ✌️thanks a lot for maintaining the tap and this repo, btw!

**Comment by ladislas** [comment]
@carlossless I've finally found the time to make the changes I wanted in the CI system.

Could you please pull `master` from us in your repo and rebase your branch on top of it. Then `push --force` the changes.

Thanks a lot!

**Comment by carlossless** [comment]
I see you already did that yourself! 🍻

**Pull request closed without merging**
