### PR TITLE
avarice 2.14

### PR DESCRIPTION
**Pull request by pthariensflame**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ladislas** [comment]
@pthariensflame thanks for the PR! I've run the workflow but there are some issues. Can you investigate? Thanks!

**Comment by pthariensflame** [comment]
I’ll take a look on the weekend!

**Comment by ladislas** [comment]
any news?

**Comment by ladislas** [comment]
@pthariensflame Closing the PR for now. Feel free to reopen a new one.

**Pull request closed without merging**
