### PR TITLE
add avr binutils size patch to keep track of it

### PR DESCRIPTION
**Pull request by ladislas**
Hi there!

When installing the formulae lately, I noticed that the patch was applying with some warning due to recent changes in binutils' size.

I cleaned it up and added it to the repo for easier tracking.

### CODE REVIEW

**Comment by ladislas** [comment]
I'll modify the forumla once this is merged

**Comment by larsimmisch** [comment]
Oh, I forgot to respond to that. Perfect, go ahead and merge it!

**Comment by leojrfs** [comment]
@ladislas @larsimmisch is this ready to merge?

**Comment by larsimmisch** [comment]
I think it is, but I didn't want to merge it because @ladislas wants/should modify the formula once this is merged, so I am waiting for him to do it.

**Comment by ladislas** [comment]
Hey there! it's been a long time! :) just merged this to a specific branch before merging to master

**Pull request merged**
